language: python
python:
- '2.7'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
    PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: rsJ5K+4dhklExfAGjVYhODGJDj5VKYce0774O9gaUwH6yGrvDFnQmpdob3p/RZXdO2VjXgn1RT1NHH8+VwJW/3+RbWItGMrjMjccXFscyuSJB4bOl20rJOedQnTXUg3WJu6cYfL4IKtungZ1+Xw5Ab3VWI6+wF2Knj/xj0c2mugIrh/EBAsx600bv8std2MJ+pnc66wPJAu/ta45MASqYk7ikWFpBg8ytmf6T7aA7HvDubf1/XzxHbnbse/ebE7au/Zu3iAWdJjIyuyY+rd6W0lHbgnx6WfCuDEZnamx+Xajt+2thPNBiz4cn0uo2vmMIJgVSlHTQK/IRr4HVZaSAaBAT+SKrSb5z7V1oLuz9g3OE3SQ8EIbyTM6Zgny50e+tnt0HaLhV189qTcK4LfE9k46AUL4/TI0BDZjf8mSY8yVDxcYcovwgTSzNF30m8+tFD5e/k+BFDdLftKCs1Zr1kXSpAK4J203c/8LKgXurS3Zs+l37VA3AHgtnjkcG0+Mee6tIXYkEPUF4dPd3cYvU91MxsjySVRBWuYlXpuxRS9QAtdr98rghGLD2EeQrcgY6T4mNJKZpRF/qBdZtF/ag1S6PxGNjszsPrsxRFhAc/T48xIV7MBFWk+BKQSxjkEUwFYhG+GE6uwVGlYbqdd39rn1eYVIhxuulp6MA8lz2yU=
  - secure: DzQSc3/QcXN4fYIK4PoIA28hUygqzZ93T58q5sTZGD2d9uY483+SGBt1qOjBqF42QI8dxvVqfI2PL8ui3qEW2jbWHLv5NOy/vbcGxX/3zbgqHWSEorTmp98Z9DgVhujARFib4BuxNkdBhMcaORXVk5sUGRBBr2grIfxB1xQ52SJis3GWY19TBBa5A4rBj6Nt9pJE9J7IQwMdmfgq0lmRko+5sBCADpdMy7lPCBhXiVrL+wb2IoYZJ3+Ek1wt9JdErMyo+yyBLzJFMo8QUk/em8FUjZDhZIYRCE8SpevB/RGuzib+LPSxgM/PVDO/vCcVGKEgM1//YKkXoHE8dMZOaLuUJTq1+zwVIdwOOt4APPmcQ1woomud6vX/rluO2PjkTRgDdq36n+8hDShQczQjhPyDF63NWHiKZpVCpybFSJxsO4GYbf+FpWu7jqPMEWyMRJxrfjmFxdqPycByNW9n8AVD5cVHpTqEL/1CXF/UyLua3eJ/pBtQHJ+3T7FXbOflkLEKAokLNYr2Nn4ckmOyd+fMss5rWJUQd5Lyhu+XxM2TTXBK2HDrrND9Q8hPNkxn0bijXS/qN0n8hIhn5P9PNOkXHSV1E7/r3b59vfsCu2u0UHpluxZmWHGX3ZGps0ux6UFBgiDqtwRqo0dPWZXoh3BRaQ0RtPtRarQOCI4f6yY=
services:
- elasticsearch
before_install:
- if [ ! -d "${GAE_PYTHONPATH}" ]; then python tools/scripts/fetch_gae_sdk.py $(dirname
  "${GAE_PYTHONPATH}"); fi
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- openssl aes-256-cbc -K $encrypted_496d8ec6abbd_key -iv $encrypted_496d8ec6abbd_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- mv .env app/
- mv knowledgemap_service_account.json app/
- gcloud auth activate-service-account --key-file service_account_secret.json
install:
- pip install -r requirements_test.txt -t lib_tests
- pip install -r app/requirements.txt -t app/lib/
- gcloud config set project profile-ciandt
- gcloud -q components update gae-python
before_script:
- sleep 10
script:
- gcloud version
- python --version
- nosetests -v --nocapture --nologcapture tests
after_success:
- sed -i bak -e "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/g" app/backend/version.py
- cd app/
- gcloud app deploy -v production --promote --verbosity=info
- python e2e_test/test_version.py
