language: python
python:
- '2.7'
env:
  global:
  - secure: UIAZe5OzfS9/yySv/5b5LMWruJaSB3478X1wZnmfmDGrZgQwz/NE9sfuxaLa88gBcqKSwqJCbbR2K8qwzoB/wup2FcLAwfBmevvYZ8Kw1nTv+tq7PZHz+eMvoKD0LIRgBQUFH2H9MyQ71GopBK9GEaO18NLAKG+cijNjqHA/x6nlwr7w6PxvWU8uFhLPp8ycJBgBS/igRcCKSVPikJsX8XJhTuLfQQ9e+CmGOAXn027RhXEYvY2sxIM9ouNbPqMqUeTQYelM0HjM9NuSvG9i3SryWeP9ixkPqma3qFqXB3yDbR1cTU/CBejlqz6W+0cg9xBt3ab21mSiPMNc0+FVNBmzcK29nIGwkGyqddpfHn38KzJsOxQQE/CwNYSphumILk/6zOpV9bYaIEAkLtLIyLoVktvY28XME++tFae6QSM4w+WsGh8ZGpMTAETqasL99woOgv5O4yCYemLSqSRxIFUnXY0yXz8xxeHcwFu3TQCSAx7C8/iqmlsegejAi3DfOOQY0t0TvvO6MTiqwbiyD6SUtC9QWDFxC5SAkDbH3/z31Ooxs4ahDrsWNHIFYSey+LwX7XE2JpmQxMq4AlWl8cHxvAbC7mVX5TPHjNCdYKham7CT9Xo61yn/S0PY+ZqhtCXROgj89DwK29lG8dPqhg/2hc82DoMskLJLqjD5fr8=
  - secure: XQeo7VNNlqx+Jv0f14b4I0Dfam6Al8pDHTGo2O1opOK/u6D0b9gwMbu34sxQI2AmKi8tjHJbeYtXavPkJmnASw7uw8uHcRV/sUtCFP6T+1KP7FfPYZObZMtIWIib4Ba1/HeBO6sm1HKfyPAGcsGvAsOP1uGfjgH6T6Bj+O+fSJm8pAPEdr/m3qLZLYr+wKpRjh6hoV3Qptpq4hKMG51lTnc0RgBvMqB+JXuWFg3FKCUxAu/4gzppV0EZK6xAEWsAOilfkOVgeRyFjwrTKxGDjx9SAMHrmSOsKYUILdYQAbgSJ2fEJ9hUHWhmvmZO9KJPWirxZnfLiGA4Bz7EF4NA9yfJmpZqKQdAZRpUdJElOiaYmovaaitul7c5lLFRJH0HnPAVHg8dMNdSKs8VsdpeRD138gKKKkmrK9dfHBrEDrm//kOEOtLnB8NPrXiyNGSfDhw7byZpT6k2XXmK1CSedTeA+0+XYDW704Vjsgi+2ks6LGGF2ZUB70fei0wC7oWzVVgOgTHtt2P2mOW7resrdwKrHbtTxrhmOgWDk6ZjtGNG9faCNH4AaUF5fOigj9YZ7GbGeG7sTRHfw/PsMFP8F6fbF4NVDO0ryrP0iE77VMDPec37e4OLJnFVnjoq3InfqRPwaprUTZlInMXeH2JNOqiwiPksuO0BHcvgKtropJU=
services:
- elasticsearch
before_script:
- sleep 10
install:
- pip install -r requirements_test.txt -t lib_tests
script:
- python --version
- nosetests -v --nocapture --nologcapture tests
