version: '2'
services:
    people-elasticsearch:
        image: elasticsearch:2.4.3
        # ports:
        #     - "9200:9200"
        #     - "9300:9300"
        # uncomment this section to have elasticsearch data persisted to a volume
        #volumes:
        #   - ./elasticsearch/data:/usr/share/elasticsearch/data
    people-api:
       build: app/
       command: "run.py production"
       environment:
         - ELASTICSEARCH_URL=http://people-elasticsearch:9200
         - GOOGLE_CLIENT_SECRET=iRZziZaSswbv3y_zAOkk1AS4
         - GOOGLE_CLIENT_ID=146680675139-6fjea6lbua391tfv4hq36hl7kqo7cr96.apps.googleusercontent.com
       depends_on:
           - people-elasticsearch
       ports:
           - "5002:5000"
    people-nginx:
       build: nginx/
       depends_on:
           - people-elasticsearch
          #  - people-api
       ports:
           - "9202:9200"
          #  - "5000:5000"
