people:
  people:
    host: https://people.cit.com.br
    user:
    pass:
  gateway:
    host: https://wsgateway.cit.com.br
    app_token:

profile:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:
