version: '2'
services:
    people-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        container_name: people-elasticsearch
        # ports:
        #   - "9200:9200"
        #   - "9300:9300"
        # uncomment this section to have elasticsearch data persisted to a volume
        volumes:
         - ~/data:/usr/share/elasticsearch/data
        environment:
          - xpack.security.enabled=false
          - xpack.monitoring.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        mem_limit: 1g
    # uncomment if you don't want to use google app engine
    # people-api:
    #    build: app/
    #    command: "run_local.py"
    #    environment:
    #      - ELASTICSEARCH_URL=http://people-elasticsearch:9200
    #      - GOOGLE_CLIENT_SECRET=iRZziZaSswbv3y_zAOkk1AS4
    #      - GOOGLE_CLIENT_ID=146680675139-6fjea6lbua391tfv4hq36hl7kqo7cr96.apps.googleusercontent.com
    #      - MODE=production
    #    depends_on:
    #        - people-elasticsearch
    #    ports:
    #        - "5002:5000"
    people-kibana:
        image: docker.elastic.co/kibana/kibana:6.2.1
        container_name: people-kibana
        depends_on:
            - people-elasticsearch
        # ports:
            # - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://people-elasticsearch:9200
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
            - xpack.reporting.enabled=false
        # volumes:
        #    - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    people-nginx:
       image: nginx:1.11.8
       container_name: people-nginx
       depends_on:
           - people-elasticsearch
           - people-kibana
       ports:
           - "9202:9202"
           - "5602:5602"
       volumes:
           - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
           - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
